version: '3.8'

services:
  app:
    build: .
    container_name: sistema_barbearia_app
    restart: always
    ports:
      - "8080:7000" # Format: HOST_PORT:CONTAINER_PORT
    environment:
      - DB_URL=jdbc:mysql://db:3306/sistema_barbearia?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - DB_USER=root
      - DB_PASSWORD=12345678
      - PORT=7000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - barbearia_net

  db:
    image: mysql:8.0
    container_name: sistema_barbearia_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_DATABASE: 'sistema_barbearia'
    ports:
      - "3307:3306" # Mapped to 3307 on host to avoid conflict with existing MySQL on 3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - barbearia_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  barbearia_net:
    driver: bridge

volumes:
  db_data:
