version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: sistema_barbearia_db
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_DATABASE: 'sistema_barbearia'
    ports:
      - "3306:3306"
    # No volumes needed for schema init, handled by Flyway in the app
    # Data is ephemeral (resets on restart) unless a volume is added here

    restart: always
