version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: sistema_barbearia_db
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_DATABASE: 'sistema_barbearia'
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/resources/setup.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
